# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb60906ac0dee38a46d4d4d19eabc8ff7644061bee6ae45aa2f74957c2013847ab9ba241c9f726c148a3b5d78f1774f067fa35fbb34450fe7c0eb9581bcf5a8b

test:
  secret_key_base: 76d4e4b68593f9b953198291d0a19ab4595c92efb9bde94cb778a307296574ef978dd1da16bf030841bdb4a80cf0ac0b51b7bef4e21b6a662d99523a897897c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
